//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string ZipCode { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
        public string CoordLong { get; set; }
        public string CoordLat { get; set; }
        public string Country { get; set; }
        public string SunriseStart { get; set; }
        public string SunriseSet { get; set; }
        public string TemperatureAvg { get; set; }
        public string TemperatureMin { get; set; }
        public string TemperatureMax { get; set; }
        public string TemperatureUnit { get; set; }
        public string HumidityValue { get; set; }
        public string HumidityUnit { get; set; }
        public string PressureValue { get; set; }
        public string PressureUnit { get; set; }
        public string WindSpeedValue { get; set; }
        public string WindSpeedName { get; set; }
        public string WindDirectionValue { get; set; }
        public string WindDirectionCode { get; set; }
        public string WindDirectionName { get; set; }
        public string CloudValue { get; set; }
        public string CloudName { get; set; }
        public string PrecipitationMode { get; set; }
        public string WeatherNumber { get; set; }
        public string WeatherValue { get; set; }
        public string WeatherIcon { get; set; }
        public Nullable<System.DateTime> LastUpdateValue { get; set; }

        public bool Empty
        {
            get { return (String.IsNullOrEmpty(CityName) && ID == 0); }
        }
    }
}
