USE [master]
GO

/****** Object:  Database [iops_dev_v1]    Script Date: 9/30/2014 1:55:16 PM ******/
CREATE DATABASE [iops_dev_v1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iops_dev_v1', FILENAME = N'C:\SQLData\Data\iops_dev_v1.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iops_dev_v1_log', FILENAME = N'C:\SQLData\Logs\iops_dev_v1_log.ldf' , SIZE = 1088KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iops_dev_v1] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iops_dev_v1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iops_dev_v1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iops_dev_v1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iops_dev_v1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iops_dev_v1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iops_dev_v1] SET ARITHABORT OFF 
GO

ALTER DATABASE [iops_dev_v1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iops_dev_v1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iops_dev_v1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iops_dev_v1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iops_dev_v1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iops_dev_v1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iops_dev_v1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iops_dev_v1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iops_dev_v1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iops_dev_v1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iops_dev_v1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iops_dev_v1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iops_dev_v1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iops_dev_v1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iops_dev_v1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iops_dev_v1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iops_dev_v1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iops_dev_v1] SET RECOVERY FULL 
GO

ALTER DATABASE [iops_dev_v1] SET  MULTI_USER 
GO

ALTER DATABASE [iops_dev_v1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iops_dev_v1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iops_dev_v1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iops_dev_v1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [iops_dev_v1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [iops_dev_v1] SET  READ_WRITE 
GO


