//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACPosition
    {
        public string AircraftType { get; set; }
        public string IATACode { get; set; }
        public string DoorPosition { get; set; }
        public Nullable<double> AC_Door_AVG_HT { get; set; }
        public Nullable<double> AC_DRIVE_COL_HT { get; set; }
    }
}
