//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACSpecification
    {
        public string IATACode { get; set; }
        public string ACType { get; set; }
        public string AircraftType { get; set; }
        public string MaxDoorSillHeight { get; set; }
        public string MinDoorSillHeight { get; set; }
        public string MinDoorSillHeight2 { get; set; }
        public string NoseToNose { get; set; }
        public string NoseToDoor { get; set; }
        public string CLToSill { get; set; }
        public string WingSpan { get; set; }
        public string OverallLength { get; set; }
        public string DoorSillAngle { get; set; }
    }
}
