//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Organizations_ContactInformation = new HashSet<Organizations_ContactInformation>();
            this.Users_ContactInformation = new HashSet<Users_ContactInformation>();
        }
    
        public System.Guid ID { get; set; }
        public string ControlField { get; set; }
        public string Name { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsDeleted { get; set; }
        public bool ReadyForArchive { get; set; }
    
        public virtual ICollection<Organizations_ContactInformation> Organizations_ContactInformation { get; set; }
        public virtual ICollection<Users_ContactInformation> Users_ContactInformation { get; set; }
    }
}
