//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iOPCOmanDBEntities : DbContext
    {
        public iOPCOmanDBEntities()
            : base("name=iOPCOmanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACPosition> ACPositions { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<ACSpecification> ACSpecifications { get; set; }
    }
}
