//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string AircraftType { get; set; }
        public string AircraftSubType { get; set; }
        public string Airline { get; set; }
        public string FlightNumber { get; set; }
        public string ArrivalAirport { get; set; }
        public string DepartureAirport { get; set; }
        public Nullable<System.DateTime> OnBoardActualTime { get; set; }
        public Nullable<System.DateTime> OnBoardScheduledTime { get; set; }
        public Nullable<System.DateTime> OnBoardEstimatedTime { get; set; }
        public Nullable<System.DateTime> OnBoardTouchDownTime { get; set; }
        public string PassengerGate { get; set; }
        public string ParkingPosition { get; set; }
        public Nullable<System.DateTime> BridgeUpdateDateTime { get; set; }
        public string DoorPosition { get; set; }
        public Nullable<double> AC_Door_AVG_HT { get; set; }
        public Nullable<double> AC_DRIVE_COL_HT { get; set; }
        public bool RTUOnIndicator { get; set; }
        public bool RTURemoteCntrl { get; set; }
    }
}
