//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iopsContext : DbContext
    {
        public iopsContext()
            : base("name=iopsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Organizations_ContactInformation> Organizations_ContactInformation { get; set; }
        public virtual DbSet<Salutation> Salutations { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<SecurityGroup> SecurityGroups { get; set; }
        public virtual DbSet<SecurityRole> SecurityRoles { get; set; }
        public virtual DbSet<SecurityTask> SecurityTasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users_ContactInformation> Users_ContactInformation { get; set; }
        public virtual DbSet<UsersXrefScreen> UsersXrefScreens { get; set; }
    }
}
