//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.UsersXrefScreens = new HashSet<UsersXrefScreen>();
        }
    
        public System.Guid ID { get; set; }
        public string ControlField { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string ScreenLayout { get; set; }
        public bool IsDeleted { get; set; }
        public bool ReadyForArchive { get; set; }
        public Nullable<int> DefaultDisplayOrder { get; set; }
        public string DefaultIconType { get; set; }
    
        public virtual ICollection<UsersXrefScreen> UsersXrefScreens { get; set; }
    }
}
