//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLL_Network_Monitoring_Bool
    {
        public System.DateTime DateAndTime { get; set; }
        public int ms { get; set; }
        public string TagName { get; set; }
        public Nullable<bool> DataValue { get; set; }
        public string Gate { get; set; }
        public string Tag { get; set; }
    }
}
