//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLL_PBB_DailyAircraftDocked
    {
        public System.DateTime DateAndTime { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate1A_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate1B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate2A_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate2B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate3A_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate3B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate4A_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate4B_PBB_DAILYAIRCRAFTDOCKED_Value { get; set; }
    }
}
