//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLL_PBB_3A_UnDockTime
    {
        public System.DateTime DateAndTime { get; set; }
        public string Airport_SLL_Term1_Zone1_Gate3A_PBB_UnDockTime_Value { get; set; }
    }
}
