//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SLL_IOPS_ReportingEntities : DbContext
    {
        public SLL_IOPS_ReportingEntities()
            : base("name=SLL_IOPS_ReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SLL_PBB_1A_DockTime> SLL_PBB_1A_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_1A_UnDockTime> SLL_PBB_1A_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_1B_DockTime> SLL_PBB_1B_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_1B_UnDockTime> SLL_PBB_1B_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_2A_DockTime> SLL_PBB_2A_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_2A_UnDockTime> SLL_PBB_2A_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_2B_DockTime> SLL_PBB_2B_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_2B_UnDockTime> SLL_PBB_2B_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_3A_DockTime> SLL_PBB_3A_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_3A_UnDockTime> SLL_PBB_3A_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_3B_DockTime> SLL_PBB_3B_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_3B_UnDockTime> SLL_PBB_3B_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_4A_DockTime> SLL_PBB_4A_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_4A_UnDockTime> SLL_PBB_4A_UnDockTime { get; set; }
        public virtual DbSet<SLL_PBB_4B_DockTime> SLL_PBB_4B_DockTime { get; set; }
        public virtual DbSet<SLL_PBB_4B_UnDockTime> SLL_PBB_4B_UnDockTime { get; set; }
        public virtual DbSet<SLL_Network_Monitoring_Bool> SLL_Network_Monitoring_Bools { get; set; }
        public virtual DbSet<SLL_PBB_AlarmLogging> SLL_PBB_AlarmLogging { get; set; }
        public virtual DbSet<SLL_PBB_WarningLogging> SLL_PBB_WarningLogging { get; set; }
        public virtual DbSet<SLL_PBB_DockTime_DataLogging> SLL_PBB_DockTime_DataLogging { get; set; }
        public virtual DbSet<SLL_PBB_UnDockTime_DataLogging> SLL_PBB_UnDockTime_DataLogging { get; set; }
        public virtual DbSet<SLL_PBB_DataLogging> SLL_PBB_DataLogging { get; set; }
        public virtual DbSet<SLL_PBB_DailyAircraftDocked> SLL_PBB_DailyAircraftDocked { get; set; }
    }
}
