//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iOps.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Users_ContactInformation = new HashSet<Users_ContactInformation>();
            this.UsersXrefScreens = new HashSet<UsersXrefScreen>();
            this.Organizations = new HashSet<Organization>();
            this.SecurityGroups = new HashSet<SecurityGroup>();
            this.SecurityRoles = new HashSet<SecurityRole>();
            this.SecurityTasks = new HashSet<SecurityTask>();
        }
    
        public System.Guid ID { get; set; }
        public string ControlField { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordDateTime { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> SalutationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool ReadyForArchive { get; set; }
    
        public virtual Salutation Salutation { get; set; }
        public virtual ICollection<Users_ContactInformation> Users_ContactInformation { get; set; }
        public virtual ICollection<UsersXrefScreen> UsersXrefScreens { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<SecurityGroup> SecurityGroups { get; set; }
        public virtual ICollection<SecurityRole> SecurityRoles { get; set; }
        public virtual ICollection<SecurityTask> SecurityTasks { get; set; }
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
